languageCode: en-us
build:
  writeStats: true
disableKinds:
  - taxonomy
  - taxonomyTerm
params:
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Github Pages](https://pages.github.com/)
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">
  # TODO EDITABLE FROM HERE
  title: Paris Frank Pouatcha
  author: Paris Frank Pouatcha
  description: The front of Paris Pouatcha
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  profile:
    name: "Paris F. Pouatcha"
    tagline: Student-Athlete
    location: "Alpharetta, Georgia"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://linkedin.com/in/paris-frank-pouatcha-00a4b1301"
        title: LinkedIn
      - icon: fab fa-instagram
        url: "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.instagram.com/parispouatcha/&ved=2ahUKEwjw376burCGAxUX_bsIHSx2DdAQFnoECBMQAQ&usg=AOvVaw3qHQcEm4F0cvcjvI0fAXDs"
        title: Instagram
      - icon: fab fa-dribbble
        url: "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.tennisrecruiting.net/player.asp%3Fid%3D870065&ved=2ahUKEwif25v1urCGAxWRnf0HHZ-TDhIQFnoECBEQAQ&usg=AOvVaw3QJI0Zoj5B0obzKxn-V92r"
        title: Tennis Recruiting page
      - icon: fab fa-twitter
        url: "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://twitter.com/ParisPouatcha&ved=2ahUKEwimkLz8u7CGAxXnhv0HHd3ECaIQFnoECBYQAQ&usg=AOvVaw0DQ4K_iTUmny5pSr8CAasT"
        title: Twitter
      - icon: fab fa-youtube
        url: "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.youtube.com/channel/UCUXo5AVXzjDW3Uu3IEAvjwA&ved=2ahUKEwjasP6hvLCGAxWvg_0HHaWdC-QQFnoECBIQAQ&usg=AOvVaw3_rhZilxt2HqMsvqnw_Ms3"
        title: Youtube
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: This is a description of the portfolio of the renowned Paris Frank Pouatcha. I am a 30 year old defi pioneer and former pro tennis player. Below you can find my hobbies, skills, side projects, and work experiences.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Entry level Financial Analyst
        dates: 2019 - *Present*
        company: Company Name
        details: |1-
          -  Sent [emails](#), managed emails
              - Chances to look at company finances.
          - Handeed coffee to higher ups.
          - Watch over budgets and finances to budjet AI projects.
      - position: NVDA intern/entry level analyst
        dates:  2030-present
        url: "#"
        company: nvidia
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Ph.D. in Engineering
        college: Emory University
        dates: 2031-2035
        thesis_title: "Effect of humans on other humans: a study of human behavior."
        thesis_url: "#"
      - degree: MBA
        college: University of Miami
        dates: 2028 - 2030
        thesis_title: "Effect of humans on other humans: a study of human behavior."
        thesis_url: "#"
      - degree: B.S. in Finance
        college: University of Oregon
        dates: 2024 - 2028
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Ethereum
        url: "#"
        description: Decentralized finance
      - title: Brave
        url: "#"
        description: WEB3.0
      - title: Pouatcha Tennis Academy
        url: "#"
        description: Tennis group
      - title: ReshapeUS
        url: "#"
        description: United States focus program
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Tennis"
        skillrating: 90
      - skill: Math
        skillrating: 80
      - skill: Computer Science
        skillrating: 65
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Crypto
      - hobby: Chess
